[package]
name = "ftime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
ctrlc = "3.4.2"
owo-colors = "4.0.0"
termination = "0.1.2"
